apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WuQingyang2/argocd-hello.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions: 'until(true == false; [.] + [1])'
