apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2
spec:
  selector:
    matchLabels:
      app: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: v2
    spec:
      containers:
      - name: v2
        image: ikubernetes/myapp:v2
        ports:
        - containerPort: 80
