apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-app-of-apps/children/nginx
    repoURL: https://github.com/god1097/argocd-hello.git
    targetRevision: HEAD
