apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3
spec:
  selector:
    matchLabels:
      app: v3
  replicas: 1
  template:
    metadata:
      labels:
        app: v3
    spec:
      containers:
      - name: v3
        image: ikubernetes/myapp:v3
        ports:
        - containerPort: 80
