apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1
spec:
  selector:
    matchLabels:
      app: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: v1
        image: ikubernetes/myapp:v1
        ports:
        - containerPort: 80
